# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Tap < Formula
  desc "Efficient MCP router for agents"
  homepage "https://github.com/fschrhunt/tap"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.2/tap_v1.0.2_darwin_arm64.tar.gz"
      sha256 "14b7ce3bea45bbde4feb2f1bb4d8cce435718091be77f9dfcd6c35a344162958"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.2/tap_v1.0.2_darwin_amd64.tar.gz"
      sha256 "2efded60b5f874ab8a906d78a29f7a8323b98813962e589f33e5015564c22d3e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.2/tap_v1.0.2_linux_arm64.tar.gz"
      sha256 "fc407fb82106331046c0b84c190530963cd00082404db8cd7278ede0223702d6"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.2/tap_v1.0.2_linux_amd64.tar.gz"
      sha256 "2a078924392cb690167180d345aafd9738d9f7d8abc1adf83ce64ed4d0df3c14"
    end
  end

  def install
    bin.install "tap"
  end

  def caveats
    <<~EOS
      Next: tap import
    EOS
  end

  test do
    assert_equal "v1.0.2", shell_output("#{bin}/tap --version").strip
  end
end
