# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Tap < Formula
  desc "Efficient MCP router for agents"
  homepage "https://github.com/fschrhunt/tap"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.0/tap_v1.0.0_darwin_arm64.tar.gz"
      sha256 "2bfbd860887aaa32df879976fbfebe708773f75a6a2174ed503112eff7fe9655"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.0/tap_v1.0.0_darwin_amd64.tar.gz"
      sha256 "2f8248cf4ab68ae48f44ed2e0317248c55e888d1ba68b4f68fea6fe5a383a3ea"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.0/tap_v1.0.0_linux_arm64.tar.gz"
      sha256 "91b1f0227c8a402dd77a7416f516bb59050660636eec1cb4bde535cb1dce73d9"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.0/tap_v1.0.0_linux_amd64.tar.gz"
      sha256 "85abfb5a209e75db6577c1b949cd8b73d29efc21d1c6e4692fda4878d2e12602"
    end
  end

  def install
    bin.install "tap"
  end

  def caveats
    <<~EOS
      Next: tap import
    EOS
  end

  test do
    assert_equal "v1.0.0", shell_output("#{bin}/tap --version").strip
  end
end
