# frozen_string_literal: true

# Generated by scripts/formula.sh for each release; edit that script, not this file.
class Tap < Formula
  desc "Efficient MCP router for agents"
  homepage "https://github.com/fschrhunt/tap"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.1/tap_v1.0.1_darwin_arm64.tar.gz"
      sha256 "6354876b7a01b1b8e722a6a8612ab571ce8e8fbb9762092060475b24e2fc7aff"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.1/tap_v1.0.1_darwin_amd64.tar.gz"
      sha256 "f253abbff7b5c3ee9bb3608497437f91ff36d18aa777a52974f9ae3e6cfa1c91"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.1/tap_v1.0.1_linux_arm64.tar.gz"
      sha256 "ebb598bea5de8a5daaddb797110975a07d00e275002a315b9141bfca6badd617"
    end
    on_intel do
      url "https://github.com/fschrhunt/tap/releases/download/v1.0.1/tap_v1.0.1_linux_amd64.tar.gz"
      sha256 "c80ef7a7f7e4d393dadad206ed659148446a92784d48d1113c489461801c1b92"
    end
  end

  def install
    bin.install "tap"
  end

  def caveats
    <<~EOS
      Next: tap import
    EOS
  end

  test do
    assert_equal "v1.0.1", shell_output("#{bin}/tap --version").strip
  end
end
